import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='bg-black min-h-screen flex'>
        <nav className='text-white flex flex-col p-20 gap-20'>
          <Link href={'./dashboard'}>Dashboard</Link>
          <Link href={'./products'}>Products</Link>
          <Link href={'./products'}>Orders</Link>
          <Link href={'./settings'}>Settings</Link>
        </nav>
        <div className='bg-white flex-grow mt-2 mr-2 p-4'>
        {children}
        </div>
        </div>
    </html>
  )
}
